-- 004_equipoise_core.sql
--
-- REFERENCE / DOCUMENTATION ONLY. This project applies DDL at startup via
-- src/index.js Server.runMigrations() (which calls src/utils/equipoise-schema.js
-- runEquipoiseMigrations); there is no migration runner. This file mirrors that DDL so the
-- schema can be reviewed/diffed in one place, matching the 001/002/003 convention.
--
-- Equipoise Benchmark & Proprietary Core (Phase 1). Stands up the durable, owned moat layer:
-- the curated decision-point benchmark, per-run panel state, the synthesizer card record, the
-- MD review loop, and the moat metric views.
--
-- Phase 1 scope: model_versions + decision_points are seeded now (npm run seed:equipoise).
-- panel_runs / specialist_positions / evidence_citations / synthesizer_outputs / md_reviews are
-- created (the views depend on them) but stay UNWRITTEN until Phase 2 pipeline wiring.
-- `refer` exists in detector_verdict for forward-compat but the detector emits only
-- converged/contested; referral is owned by synthesizer_outputs.route_to_human.
--
-- PHI note: keep queries.patient_context DE-IDENTIFIED (age band, activity level, relevant
-- comorbidities — never names, MRNs, DOBs, free-text identifiers).

-- ---------------------------------------------------------------------------
-- Enumerated types. body_region / decision_type are intentionally TEXT (the orthopedic
-- taxonomy grows — e.g. which_intervention — without a migration each time).
-- Applied with a DO/EXCEPTION guard in code (CREATE TYPE has no IF NOT EXISTS).
-- ---------------------------------------------------------------------------
CREATE TYPE detector_verdict   AS ENUM ('converged', 'contested', 'refer');
CREATE TYPE card_status        AS ENUM ('consensus', 'contested', 'refer');
CREATE TYPE specialist_agent   AS ENUM ('orthotriage', 'pain_whisperer', 'movement_detective', 'strength_sage', 'mind_mender');
CREATE TYPE stance             AS ENUM ('option_a', 'option_b', 'abstain');
CREATE TYPE equipoise_label    AS ENUM ('genuine_equipoise', 'settled_conservative', 'settled_operative', 'evolving');
CREATE TYPE label_provenance   AS ENUM ('literature', 'guideline', 'expert_consensus', 'md_adjudication');
CREATE TYPE study_type         AS ENUM ('rct', 'systematic_review', 'meta_analysis', 'cohort', 'case_control', 'case_series', 'guideline', 'expert_opinion');
CREATE TYPE evidence_grade     AS ENUM ('high', 'moderate', 'low', 'very_low');
CREATE TYPE population_match    AS ENUM ('match', 'partial', 'mismatch', 'unknown');
CREATE TYPE route_reason       AS ENUM ('operative_decision', 'contested_equipoise', 'population_mismatch', 'low_support', 'risk_category', 'none');
CREATE TYPE run_kind           AS ENUM ('production', 'benchmark_probe', 'sham_control', 'reproducibility');
CREATE TYPE review_status      AS ENUM ('pending', 'approved', 'corrected', 'rejected');
CREATE TYPE dp_detected_by     AS ENUM ('manual', 'classifier');

-- ---------------------------------------------------------------------------
-- model_versions — which Claude model produced a run. Spine of every over-time metric.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS model_versions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider      TEXT        NOT NULL DEFAULT 'anthropic',
    model_string  TEXT        NOT NULL,
    display_name  TEXT,
    released_at   TIMESTAMPTZ,
    notes         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, model_string)
);

-- ---------------------------------------------------------------------------
-- decision_points — the curated equipoise benchmark taxonomy. THE moat catalog.
-- Seeded from db/seeds/decision-points.csv (npm run seed:equipoise).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS decision_points (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug               TEXT        NOT NULL UNIQUE,
    title              TEXT        NOT NULL,
    body_region        TEXT        NOT NULL,
    decision_type      TEXT        NOT NULL,
    is_operative       BOOLEAN     NOT NULL DEFAULT false,
    canonical_question TEXT        NOT NULL,
    option_a_label     TEXT        NOT NULL,
    option_b_label     TEXT        NOT NULL,
    expected_equipoise equipoise_label NOT NULL,
    equipoise_rationale TEXT,
    label_provenance   label_provenance,
    label_source_refs  JSONB,
    is_active          BOOLEAN     NOT NULL DEFAULT true,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- queries — every query run through the platform (live OR curated benchmark probe).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS queries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_text         TEXT        NOT NULL,
    is_benchmark     BOOLEAN     NOT NULL DEFAULT false,
    patient_context  JSONB,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- query_decision_points — a query may surface more than one decision point.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS query_decision_points (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id          BIGINT      NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
    decision_point_id BIGINT      NOT NULL REFERENCES decision_points(id),
    detected_by       dp_detected_by NOT NULL DEFAULT 'classifier',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (query_id, decision_point_id)
);

-- ---------------------------------------------------------------------------
-- panel_runs — one execution of the panel pipeline, scoped to a decision point.
-- detector_verdict is the AUTHORITATIVE output of the validated detector. (Phase 2 writer.)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS panel_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id          BIGINT      NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
    decision_point_id BIGINT      NOT NULL REFERENCES decision_points(id),
    model_version_id  BIGINT      NOT NULL REFERENCES model_versions(id),
    session_id        TEXT,
    detector_verdict  detector_verdict NOT NULL,
    split_summary     JSONB,
    run_kind          run_kind    NOT NULL DEFAULT 'production',
    run_index         INTEGER     NOT NULL DEFAULT 1,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_panel_runs_dp      ON panel_runs (decision_point_id);
CREATE INDEX IF NOT EXISTS idx_panel_runs_model   ON panel_runs (model_version_id);
CREATE INDEX IF NOT EXISTS idx_panel_runs_verdict ON panel_runs (detector_verdict);
CREATE INDEX IF NOT EXISTS idx_panel_runs_query   ON panel_runs (query_id);

-- ---------------------------------------------------------------------------
-- specialist_positions — per agent, per run. initial vs final = the deliberation delta.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS specialist_positions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_run_id   BIGINT      NOT NULL REFERENCES panel_runs(id) ON DELETE CASCADE,
    agent          specialist_agent NOT NULL,
    initial_stance stance      NOT NULL,
    final_stance   stance      NOT NULL,
    revised        BOOLEAN     GENERATED ALWAYS AS (initial_stance <> final_stance) STORED,
    confidence     NUMERIC(3,2) CHECK (confidence BETWEEN 0 AND 1),
    reasoning      TEXT,
    revised_on     TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (panel_run_id, agent)
);
CREATE INDEX IF NOT EXISTS idx_positions_run ON specialist_positions (panel_run_id);

-- ---------------------------------------------------------------------------
-- evidence_citations — claim-level grounded citations (Research-agent output, Phase 2.5).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS evidence_citations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_run_id     BIGINT      NOT NULL REFERENCES panel_runs(id) ON DELETE CASCADE,
    supports_stance  stance,
    claim_text       TEXT        NOT NULL,
    pmid             TEXT,
    title            TEXT,
    study_type       study_type,
    evidence_grade   evidence_grade,
    population_match population_match NOT NULL DEFAULT 'unknown',
    accepted         BOOLEAN     NOT NULL DEFAULT true,
    rationale        TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_citations_run  ON evidence_citations (panel_run_id);
CREATE INDEX IF NOT EXISTS idx_citations_pmid ON evidence_citations (pmid);

-- ---------------------------------------------------------------------------
-- synthesizer_outputs — the rendered clinician card. status MAY differ from detector_verdict
-- ONLY when evidence collapsed a contest (collapsed = true, collapse_reason required).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS synthesizer_outputs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_run_id    BIGINT      NOT NULL UNIQUE REFERENCES panel_runs(id) ON DELETE CASCADE,
    status          card_status NOT NULL,
    collapsed       BOOLEAN     NOT NULL DEFAULT false,
    collapse_reason TEXT,
    route_to_human  BOOLEAN     NOT NULL DEFAULT false,
    route_reason    route_reason NOT NULL DEFAULT 'none',
    support_score   NUMERIC(3,2) CHECK (support_score BETWEEN 0 AND 1),
    card_json       JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT collapse_needs_reason CHECK (NOT collapsed OR collapse_reason IS NOT NULL)
);

-- ---------------------------------------------------------------------------
-- md_reviews — oversight decisions. The labeling loop: agreed_with_detector +
-- corrected_equipoise_label feed improvements back into decision_points.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS md_reviews (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_run_id              BIGINT      NOT NULL REFERENCES panel_runs(id) ON DELETE CASCADE,
    synthesizer_output_id     BIGINT      REFERENCES synthesizer_outputs(id),
    reviewer_id               TEXT,
    review_status             review_status NOT NULL DEFAULT 'pending',
    agreed_with_detector      BOOLEAN,
    corrected_equipoise_label equipoise_label,
    hallucination_flags       JSONB,
    notes                     TEXT,
    reviewed_at               TIMESTAMPTZ,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_reviews_run    ON md_reviews (panel_run_id);
CREATE INDEX IF NOT EXISTS idx_reviews_status ON md_reviews (review_status);

-- ===========================================================================
-- METRICS AS QUERIES — the moat metrics. Views, not pipelines.
-- ===========================================================================
CREATE OR REPLACE VIEW v_convergence_by_model AS
SELECT
    dp.slug,
    dp.title,
    mv.model_string,
    mv.released_at,
    COUNT(*)                                                     AS n_runs,
    AVG((pr.detector_verdict = 'converged')::int)::numeric(4,3) AS convergence_rate,
    AVG((pr.detector_verdict = 'contested')::int)::numeric(4,3) AS divergence_rate
FROM panel_runs pr
JOIN decision_points dp ON dp.id = pr.decision_point_id
JOIN model_versions  mv ON mv.id = pr.model_version_id
WHERE pr.run_kind IN ('production', 'benchmark_probe', 'reproducibility')
GROUP BY dp.slug, dp.title, mv.model_string, mv.released_at;

CREATE OR REPLACE VIEW v_benchmark_accuracy AS
SELECT
    dp.slug,
    dp.expected_equipoise,
    mv.model_string,
    COUNT(*) AS n_runs,
    AVG(
      CASE
        WHEN dp.expected_equipoise = 'genuine_equipoise'
             AND pr.detector_verdict = 'contested' THEN 1
        WHEN dp.expected_equipoise IN ('settled_conservative','settled_operative')
             AND pr.detector_verdict = 'converged' THEN 1
        ELSE 0
      END
    )::numeric(4,3) AS detector_hit_rate
FROM panel_runs pr
JOIN decision_points dp ON dp.id = pr.decision_point_id
JOIN model_versions  mv ON mv.id = pr.model_version_id
WHERE pr.run_kind = 'benchmark_probe'
  AND dp.expected_equipoise <> 'evolving'
GROUP BY dp.slug, dp.expected_equipoise, mv.model_string;

CREATE OR REPLACE VIEW v_detector_md_agreement AS
SELECT
    dp.slug,
    COUNT(*) FILTER (WHERE r.agreed_with_detector IS NOT NULL) AS n_reviewed,
    AVG((r.agreed_with_detector)::int)::numeric(4,3)           AS md_agreement_rate
FROM md_reviews r
JOIN panel_runs pr      ON pr.id = r.panel_run_id
JOIN decision_points dp ON dp.id = pr.decision_point_id
WHERE r.review_status <> 'pending'
GROUP BY dp.slug;
