/**
 * Equipoise Benchmark & Proprietary Core — schema migrations (Phase 1).
 *
 * Stands up the durable, owned layer behind AequOs's repositioning to a calibrated
 * equipoise-mapping instrument: the curated decision-point benchmark, per-run panel state,
 * the synthesizer card record, the MD review loop, and the moat metric views.
 *
 * Companion to the design sketch (aequos_equipoise_schema.sql). Architectural invariants
 * preserved here:
 *   - panel_runs.detector_verdict is AUTHORITATIVE; the synthesizer's card status lives on a
 *     separate column (synthesizer_outputs.status) and can only diverge via an explicit,
 *     reason-required `collapsed`.
 *   - decision_type / body_region stay TEXT (the orthopedic taxonomy grows without migrations).
 *   - decision_points.expected_equipoise is ground truth; md_reviews close the labeling loop.
 *
 * Idempotent + additive: safe to run on every startup. Mirrors the established runMigrations()
 * pattern in src/index.js — Neon HTTP runs ONE statement per call, so each enum/table/index/view
 * is its own awaited query. Enums use a DO/EXCEPTION guard because Postgres has no
 * `CREATE TYPE IF NOT EXISTS`.
 *
 * Phase 1 scope note: panel_runs / specialist_positions / evidence_citations /
 * synthesizer_outputs / md_reviews are created now (the views depend on them) but stay UNWRITTEN
 * until the Phase 2 pipeline wiring. `refer` exists in the detector_verdict enum for forward-compat
 * (avoids a painful ALTER TYPE later) but the detector emits only converged/contested; referral is
 * owned by synthesizer_outputs.route_to_human.
 */

/**
 * @param {import('@neondatabase/serverless').NeonQueryFunction<any, any>} sql
 * @returns {Promise<void>}
 */
export async function runEquipoiseMigrations(sql) {
  if (!sql) return; // no DB configured — skip silently (dev/tests)

  // ---- Enumerated types ----
  // CREATE TYPE has no IF NOT EXISTS, so each is wrapped in a DO/EXCEPTION guard for idempotency.
  // Statements are fully static (no JS interpolation) so the Neon tag sends them as raw DDL.
  await sql`DO $$ BEGIN CREATE TYPE detector_verdict AS ENUM ('converged','contested','refer'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE card_status AS ENUM ('consensus','contested','refer'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE specialist_agent AS ENUM ('orthotriage','pain_whisperer','movement_detective','strength_sage','mind_mender'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE stance AS ENUM ('option_a','option_b','abstain'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE equipoise_label AS ENUM ('genuine_equipoise','settled_conservative','settled_operative','evolving'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE label_provenance AS ENUM ('literature','guideline','expert_consensus','md_adjudication'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE study_type AS ENUM ('rct','systematic_review','meta_analysis','cohort','case_control','case_series','guideline','expert_opinion'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE evidence_grade AS ENUM ('high','moderate','low','very_low'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE population_match AS ENUM ('match','partial','mismatch','unknown'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE route_reason AS ENUM ('operative_decision','contested_equipoise','population_mismatch','low_support','risk_category','none'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE run_kind AS ENUM ('production','benchmark_probe','sham_control','reproducibility'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE review_status AS ENUM ('pending','approved','corrected','rejected'); EXCEPTION WHEN duplicate_object THEN null; END $$`;
  await sql`DO $$ BEGIN CREATE TYPE dp_detected_by AS ENUM ('manual','classifier'); EXCEPTION WHEN duplicate_object THEN null; END $$`;

  // ---- model_versions: the spine of every over-time metric ----
  await sql`CREATE TABLE IF NOT EXISTS model_versions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider      TEXT        NOT NULL DEFAULT 'anthropic',
    model_string  TEXT        NOT NULL,
    display_name  TEXT,
    released_at   TIMESTAMPTZ,
    notes         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, model_string)
  )`;

  // ---- decision_points: the curated equipoise benchmark taxonomy (THE moat catalog) ----
  await sql`CREATE TABLE IF NOT EXISTS decision_points (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug               TEXT        NOT NULL UNIQUE,
    title              TEXT        NOT NULL,
    body_region        TEXT        NOT NULL,
    decision_type      TEXT        NOT NULL,
    is_operative       BOOLEAN     NOT NULL DEFAULT false,
    canonical_question TEXT        NOT NULL,
    option_a_label     TEXT        NOT NULL,
    option_b_label     TEXT        NOT NULL,
    expected_equipoise equipoise_label NOT NULL,
    equipoise_rationale TEXT,
    label_provenance   label_provenance,
    label_source_refs  JSONB,
    is_active          BOOLEAN     NOT NULL DEFAULT true,
    absolute_indication BOOLEAN    NOT NULL DEFAULT false,
    is_pediatric       BOOLEAN     NOT NULL DEFAULT false,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
  )`;
  // Additive migration for DBs whose decision_points predates absolute_indication. Red-flag DPs
  // (overwhelming-operative with bailout-only exceptions, e.g. cord compression, open joint) carry
  // this flag: the detector may over-flag them as contested, but that routes to urgent surgical
  // consultation (product-safe), so the benchmark SEGMENTS them rather than scoring them as equipoise.
  await sql`ALTER TABLE decision_points ADD COLUMN IF NOT EXISTS absolute_indication BOOLEAN NOT NULL DEFAULT false`;
  // Additive migration: pediatric DPs are routed to the remodeling/growth archetype axis (children are
  // not small adults) instead of the adult demand×surgical-risk axis. Seeded from pediatric-indications.json.
  await sql`ALTER TABLE decision_points ADD COLUMN IF NOT EXISTS is_pediatric BOOLEAN NOT NULL DEFAULT false`;

  // ---- Sentinel anchor for PRODUCTION panel runs (Phase 2b) ----
  // A real consult surfaces ad-hoc, triage-framed decision points that don't map 1:1 to a curated
  // benchmark slug, but panel_runs.decision_point_id is a NOT NULL FK. This single infrastructure
  // row anchors every production panel until a Phase 2c slug-classifier splits them per-slug. It is
  // labeled 'evolving' so v_benchmark_accuracy (which filters expected_equipoise <> 'evolving' AND
  // run_kind = 'benchmark_probe') NEVER scores it — the curated 122-row catalog stays pure. The
  // consult's real question/options/verdict live in panel_runs.split_summary + synthesizer_outputs.
  await sql`INSERT INTO decision_points
      (slug, title, body_region, decision_type, is_operative, canonical_question,
       option_a_label, option_b_label, expected_equipoise, label_provenance, absolute_indication)
    VALUES
      ('production-unclassified', 'Production (unclassified consult decision)', 'unspecified',
       'unclassified', false, 'Ad-hoc decision point surfaced by a live consult (see split_summary).',
       'option_a', 'option_b', 'evolving', 'expert_consensus', false)
    ON CONFLICT (slug) DO NOTHING`;

  // ---- queries: every query run through the platform (live OR curated benchmark probe) ----
  await sql`CREATE TABLE IF NOT EXISTS queries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_text         TEXT        NOT NULL,
    is_benchmark     BOOLEAN     NOT NULL DEFAULT false,
    patient_context  JSONB,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
  )`;

  // ---- query_decision_points: a query may surface more than one decision point ----
  await sql`CREATE TABLE IF NOT EXISTS query_decision_points (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id          BIGINT      NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
    decision_point_id BIGINT      NOT NULL REFERENCES decision_points(id),
    detected_by       dp_detected_by NOT NULL DEFAULT 'classifier',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (query_id, decision_point_id)
  )`;

  // ---- panel_runs: one pipeline execution; detector_verdict is the AUTHORITATIVE moat signal ----
  await sql`CREATE TABLE IF NOT EXISTS panel_runs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id          BIGINT      NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
    decision_point_id BIGINT      NOT NULL REFERENCES decision_points(id),
    model_version_id  BIGINT      NOT NULL REFERENCES model_versions(id),
    session_id        TEXT,
    detector_verdict  detector_verdict NOT NULL,
    split_summary     JSONB,
    run_kind          run_kind    NOT NULL DEFAULT 'production',
    run_index         INTEGER     NOT NULL DEFAULT 1,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
  )`;
  await sql`CREATE INDEX IF NOT EXISTS idx_panel_runs_dp      ON panel_runs (decision_point_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_panel_runs_model   ON panel_runs (model_version_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_panel_runs_verdict ON panel_runs (detector_verdict)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_panel_runs_query   ON panel_runs (query_id)`;

  // ---- specialist_positions: per agent per run; initial vs final = the deliberation delta ----
  await sql`CREATE TABLE IF NOT EXISTS specialist_positions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_run_id   BIGINT      NOT NULL REFERENCES panel_runs(id) ON DELETE CASCADE,
    agent          specialist_agent NOT NULL,
    initial_stance stance      NOT NULL,
    final_stance   stance      NOT NULL,
    revised        BOOLEAN     GENERATED ALWAYS AS (initial_stance <> final_stance) STORED,
    confidence     NUMERIC(3,2) CHECK (confidence BETWEEN 0 AND 1),
    reasoning      TEXT,
    revised_on     TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (panel_run_id, agent)
  )`;
  await sql`CREATE INDEX IF NOT EXISTS idx_positions_run ON specialist_positions (panel_run_id)`;

  // ---- evidence_citations: claim-level grounded citations (Research-agent output, Phase 2.5) ----
  await sql`CREATE TABLE IF NOT EXISTS evidence_citations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_run_id     BIGINT      NOT NULL REFERENCES panel_runs(id) ON DELETE CASCADE,
    supports_stance  stance,
    claim_text       TEXT        NOT NULL,
    pmid             TEXT,
    title            TEXT,
    study_type       study_type,
    evidence_grade   evidence_grade,
    population_match population_match NOT NULL DEFAULT 'unknown',
    accepted         BOOLEAN     NOT NULL DEFAULT true,
    rationale        TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
  )`;
  await sql`CREATE INDEX IF NOT EXISTS idx_citations_run  ON evidence_citations (panel_run_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_citations_pmid ON evidence_citations (pmid)`;

  // ---- synthesizer_outputs: the rendered clinician card; status MAY differ only on collapse ----
  await sql`CREATE TABLE IF NOT EXISTS synthesizer_outputs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_run_id    BIGINT      NOT NULL UNIQUE REFERENCES panel_runs(id) ON DELETE CASCADE,
    status          card_status NOT NULL,
    collapsed       BOOLEAN     NOT NULL DEFAULT false,
    collapse_reason TEXT,
    route_to_human  BOOLEAN     NOT NULL DEFAULT false,
    route_reason    route_reason NOT NULL DEFAULT 'none',
    support_score   NUMERIC(3,2) CHECK (support_score BETWEEN 0 AND 1),
    card_json       JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT collapse_needs_reason CHECK (NOT collapsed OR collapse_reason IS NOT NULL)
  )`;

  // ---- md_reviews: oversight decisions — the labeling loop back into decision_points ----
  await sql`CREATE TABLE IF NOT EXISTS md_reviews (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panel_run_id              BIGINT      NOT NULL REFERENCES panel_runs(id) ON DELETE CASCADE,
    synthesizer_output_id     BIGINT      REFERENCES synthesizer_outputs(id),
    reviewer_id               TEXT,
    review_status             review_status NOT NULL DEFAULT 'pending',
    agreed_with_detector      BOOLEAN,
    corrected_equipoise_label equipoise_label,
    hallucination_flags       JSONB,
    notes                     TEXT,
    reviewed_at               TIMESTAMPTZ,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now()
  )`;
  await sql`CREATE INDEX IF NOT EXISTS idx_reviews_run    ON md_reviews (panel_run_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_reviews_status ON md_reviews (review_status)`;

  // ---- Metrics as queries (moat metrics): views, not pipelines ----
  await sql`CREATE OR REPLACE VIEW v_convergence_by_model AS
    SELECT
      dp.slug,
      dp.title,
      mv.model_string,
      mv.released_at,
      COUNT(*)                                                     AS n_runs,
      AVG((pr.detector_verdict = 'converged')::int)::numeric(4,3) AS convergence_rate,
      AVG((pr.detector_verdict = 'contested')::int)::numeric(4,3) AS divergence_rate
    FROM panel_runs pr
    JOIN decision_points dp ON dp.id = pr.decision_point_id
    JOIN model_versions  mv ON mv.id = pr.model_version_id
    WHERE pr.run_kind IN ('production', 'benchmark_probe', 'reproducibility')
    GROUP BY dp.slug, dp.title, mv.model_string, mv.released_at`;

  await sql`CREATE OR REPLACE VIEW v_benchmark_accuracy AS
    SELECT
      dp.slug,
      dp.expected_equipoise,
      mv.model_string,
      COUNT(*) AS n_runs,
      AVG(
        CASE
          WHEN dp.expected_equipoise = 'genuine_equipoise'
               AND pr.detector_verdict = 'contested' THEN 1
          WHEN dp.expected_equipoise IN ('settled_conservative','settled_operative')
               AND pr.detector_verdict = 'converged' THEN 1
          ELSE 0
        END
      )::numeric(4,3) AS detector_hit_rate,
      dp.absolute_indication
    FROM panel_runs pr
    JOIN decision_points dp ON dp.id = pr.decision_point_id
    JOIN model_versions  mv ON mv.id = pr.model_version_id
    WHERE pr.run_kind = 'benchmark_probe'
      AND dp.expected_equipoise <> 'evolving'
    GROUP BY dp.slug, dp.expected_equipoise, dp.absolute_indication, mv.model_string`;

  await sql`CREATE OR REPLACE VIEW v_detector_md_agreement AS
    SELECT
      dp.slug,
      COUNT(*) FILTER (WHERE r.agreed_with_detector IS NOT NULL) AS n_reviewed,
      AVG((r.agreed_with_detector)::int)::numeric(4,3)           AS md_agreement_rate
    FROM md_reviews r
    JOIN panel_runs pr      ON pr.id = r.panel_run_id
    JOIN decision_points dp ON dp.id = pr.decision_point_id
    WHERE r.review_status <> 'pending'
    GROUP BY dp.slug`;

  // ---- v_evidence_population_coverage: Phase 2.5 evidence population-coverage analytics ----
  // Read-only OBSERVATION of the annotation layer (NEVER feedback into the panel/routing — consistent
  // with the pure-annotation boundary). Aggregates the population_match that evidence-research.js
  // writes on every evidence_citations row, at slug × model grain over production panels. Surfaces
  // where the literature lags the real patient population: per-decision mismatch_rate, and the
  // panel-grain count of panels where NO citation cleared the strict acceptance bar (an equipoise
  // split with zero population-relevant evidence behind either side — the actionable MD-dashboard row,
  // and a prompt for the md_reviews human loop).
  await sql`CREATE OR REPLACE VIEW v_evidence_population_coverage AS
    WITH panel_evidence AS (
      SELECT pr.id AS panel_run_id,
             COUNT(*) FILTER (WHERE ec.accepted) AS n_accepted
      FROM panel_runs pr
      JOIN evidence_citations ec ON ec.panel_run_id = pr.id
      WHERE pr.run_kind = 'production'
      GROUP BY pr.id
    )
    SELECT
      dp.slug,
      dp.title,
      mv.model_string,
      COUNT(*)                                                       AS n_citations,
      COUNT(*) FILTER (WHERE ec.population_match = 'match')          AS n_match,
      COUNT(*) FILTER (WHERE ec.population_match = 'partial')        AS n_partial,
      COUNT(*) FILTER (WHERE ec.population_match = 'mismatch')       AS n_mismatch,
      COUNT(*) FILTER (WHERE ec.population_match = 'unknown')        AS n_unknown,
      AVG((ec.population_match = 'mismatch')::int)::numeric(4,3)     AS mismatch_rate,
      COUNT(DISTINCT pr.id)                                          AS n_panels,
      COUNT(DISTINCT pr.id) FILTER (WHERE pe.n_accepted = 0)         AS n_panels_no_accepted_evidence
    FROM evidence_citations ec
    JOIN panel_runs      pr ON pr.id = ec.panel_run_id AND pr.run_kind = 'production'
    JOIN decision_points dp ON dp.id = pr.decision_point_id
    JOIN model_versions  mv ON mv.id = pr.model_version_id
    JOIN panel_evidence  pe ON pe.panel_run_id = pr.id
    GROUP BY dp.slug, dp.title, mv.model_string`;
}

export default runEquipoiseMigrations;
